<?php
/**
 * Local URL scheme compatibility.
 */
defined( 'ABSPATH' ) || exit;

/**
 * Keep local asset URLs on the same scheme as the current request.
 *
 * Local can store `siteurl` as HTTPS while the browser opens HTTP. When the
 * local certificate is not trusted, that blocks CSS/JS/images and makes the UI
 * look unstyled. This filter is limited to same-host URLs in local env only.
 *
 * @param string $url URL generated by WordPress.
 * @return string
 */
function bsc_local_match_request_scheme( string $url ): string {
	if ( '' === $url || 'local' !== wp_get_environment_type() ) {
		return $url;
	}

	if ( empty( $_SERVER['HTTP_HOST'] ) ) {
		return $url;
	}

	$request_host = sanitize_text_field( wp_unslash( $_SERVER['HTTP_HOST'] ) );
	$request_host = strtolower( preg_replace( '/:\d+$/', '', $request_host ) ?? $request_host );
	$url_host     = wp_parse_url( $url, PHP_URL_HOST );

	if ( ! is_string( $url_host ) || strtolower( $url_host ) !== $request_host ) {
		return $url;
	}

	return set_url_scheme( $url, is_ssl() ? 'https' : 'http' );
}

foreach (
	array(
		'content_url',
		'plugins_url',
		'script_loader_src',
		'style_loader_src',
		'stylesheet_directory_uri',
		'template_directory_uri',
		'theme_root_uri',
		'wp_get_attachment_url',
	) as $bsc_local_scheme_filter
) {
	add_filter( $bsc_local_scheme_filter, 'bsc_local_match_request_scheme', PHP_INT_MAX );
}

unset( $bsc_local_scheme_filter );
